fix: make PKCS#7 parameter optional as per RFC 5280
digitalbazaar/forge pull request #830
Opened 2020-11-16 05:49 UTC by troyfactor4

Fixes #829

2020-11-17 15:18 UTC, dlongley requested changes
Thanks! This PR needs some additional changes down in the `_encryptedContentToAsn1` function to handle when the parameter is `null` or `undefined` (!ec.parameter). That should ensure we can still round trip (parse and reserialize) here.

2020-11-17 17:15 UTC, troyfactor4 commented
Good catch! Here is my proposed remedy. I've checked asn1.create seems to happily take undefined in an array and remove it. Let me know if you think this is an ok way to handle it.

2020-11-18 20:14 UTC, dlongley commented on lib/pkcs7.js
> +      parameter: capture.encParameter ? capture.encParameter.value : null,
```suggestion
      parameter: capture.encParameter ? capture.encParameter.value : undefined,
```

2020-11-18 20:14 UTC, dlongley commented on lib/pkcs7.js
> +      )
```suggestion
      !ec.parameter ?
        undefined :
        asn1.create(
          asn1.Class.UNIVERSAL, asn1.Type.OCTETSTRING, false,
          ec.parameter.getBytes())
```

2020-11-18 20:15 UTC, dlongley approved these changes

2020-11-18 20:15 UTC, merged

2020-11-18 20:15 UTC, dlongley commented
Thanks!

2020-11-19 00:37 UTC, troyfactor4 commented
Awesome! Really appreciate the help and fast turn around.

I don't suppose I could beg you to look at #400 when you have 5 min free? Pretty please?

2021-08-22 15:51 UTC, eiygy reviewed
- [ ]